title = "16th Workshop on Virtualization in High-Performance Cloud Computing"
baseURL = "https://vhpc.org"
languageCode = "en-us"
theme = "ananke"
#themesDir = "../.."
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "16th Workshop on Virtualization in High-Performance Cloud Computing"
    weight = 1
    contentDir = "content/en"
  #[languages.fr]
  #  title = "Mon blogue"
  #  weight = 2
  #  contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = "/images/vhpclogo.png"
  #description = "held in conjunction with ISC-HPC 2022, Hamburg, DE, May 29th - Jun 2nd 2022"
  #description = "blah"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/hamburg.png"
  recent_posts_number = 5
  body_classes = "avenir bg-light-gray"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/anan0s"
